==============================
 Alert react native  
==============================
import React, { useState } from "react"; import { View, StyleSheet, Button, Alert } from "react-native";  const App = () => {   const createTwoButtonAlert = () =>     Alert.alert(       "Alert Title",       "My Alert Msg",       [         {           text: "Cancel",           onPress: () => console.log("Cancel Pressed"),           style: "cancel"         },         { text: "OK", onPress: () => console.log("OK Pressed") }       ]     );    const createThreeButtonAlert = () =>     Alert.alert(       "Alert Title",       "My Alert Msg",       [         {           text: "Ask me later",           onPress: () => console.log("Ask me later pressed")         },         {           text: "Cancel",           onPress: () => console.log("Cancel Pressed"),           style: "cancel"         },         { text: "OK", onPress: () => console.log("OK Pressed") }       ]     );    return (     <View style={styles.container}>       <Button title={"2-Button Alert"} onPress={createTwoButtonAlert} />       <Button title={"3-Button Alert"} onPress={createThreeButtonAlert} />     </View>   ); }  const styles = StyleSheet.create({   container: {     flex: 1,     justifyContent: "space-around",     alignItems: "center"   } });  export default App;
// Works on both Android and iOS Alert.alert(   'Alert Title',   'My Alert Msg',   [     {text: 'Ask me later', onPress: () => console.log('Ask me later pressed')},     {       text: 'Cancel',       onPress: () => console.log('Cancel Pressed'),       style: 'cancel',     },     {text: 'OK', onPress: () => console.log('OK Pressed')},   ],   {cancelable: false}, ); 
//I was going through the same thing and I found a way to style it. in styles.xml add:  //In AppTheme add:  <item name="android:alertDialogTheme">@style/AlertDialogTheme</item> //Then:  <style name="AlertDialogTheme" parent="Theme.AppCompat.Dialog.Alert">     <item name="android:background">#00397F</item>     <item name="android:colorPrimary">#00397F</item>     <item name="android:colorAccent">#0AAEEF</item>     <item name="android:buttonBarNegativeButtonStyle">@style/NegativeButtonStyle</item>     <item name="android:buttonBarPositiveButtonStyle">@style/PositiveButtonStyle</item> </style>  <style name="NegativeButtonStyle" parent="Widget.AppCompat.Button.ButtonBar.AlertDialog">     <item name="android:textColor">#F0A90F</item> </style>  <style name="PositiveButtonStyle" parent="Widget.AppCompat.Button.ButtonBar.AlertDialog">     <item name="android:textColor">#F0A90F</item> </style> //Play with it and add more customized values as needed.
  
==============================
158 at  2021-10-29T15:22:52.000Z
==============================
