==============================
 JS Fetch API Post Request  
==============================
(async () => {   const rawResponse = await fetch('https://httpbin.org/post', {     method: 'POST',     headers: {       'Accept': 'application/json',       'Content-Type': 'application/json'     },     body: JSON.stringify({a: 1, b: 'Textual content'})   });   const content = await rawResponse.json();    console.log(content); })();
fetch('https://example.com/profile', {   method: 'POST',   headers: { 'Content-Type': 'application/json' },   body: JSON.stringify({   	'foo': 'bar'   }), })   .then((res) => res.json())   .then((data) => {     // Do some stuff ...   })   .catch((err) => console.log(err));
componentDidMount() {     // Simple POST request with a JSON body using fetch     const requestOptions = {         method: 'POST',         headers: { 'Content-Type': 'application/json' },         body: JSON.stringify({ title: 'React POST Request Example' })     };     fetch('https://jsonplaceholder.typicode.com/posts', requestOptions)         .then(response => response.json())         .then(data => this.setState({ postId: data.id })); }
async function postData(url = '', data = {}) {   // Default options are marked with *   const response = await fetch(url, {     method: 'POST', // *GET, POST, PUT, DELETE, etc.     mode: 'cors', // no-cors, *cors, same-origin     cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached     credentials: 'same-origin', // include, *same-origin, omit     headers: {       'Content-Type': 'application/json'       // 'Content-Type': 'application/x-www-form-urlencoded',     },     redirect: 'follow', // manual, *follow, error     referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url     body: JSON.stringify(data) // body data type must match "Content-Type" header   });   return response.json(); // parses JSON response into native JavaScript objects }  postData('', )   .then(data => {     console.log(data); // JSON data parsed by `data.json()` call   });
// Example POST method implementation: async function postData(url = '', data = {}) {   // Default options are marked with *   const response = await fetch(url, {     method: 'POST', // *GET, POST, PUT, DELETE, etc.     mode: 'cors', // no-cors, *cors, same-origin     cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached     credentials: 'same-origin', // include, *same-origin, omit     headers: {       'Content-Type': 'application/json'       // 'Content-Type': 'application/x-www-form-urlencoded',     },     redirect: 'follow', // manual, *follow, error     referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url     body: JSON.stringify(data) // body data type must match "Content-Type" header   });   return response.json(); // parses JSON response into native JavaScript objects }  postData('https://example.com/answer', { answer: 42 })   .then(data => {     console.log(data); // JSON data parsed by `data.json()` call   }); 
  
==============================
261 at  2021-10-29T15:22:52.000Z
==============================
